### ISSUE TITLE
API key not valid

### ISSUE THREAD

**Issue by behhak** [firebase/codelab-friendlychat-android#188]
I'm learning firebase through Firebase Android Codelab - Build Friendly Chat
I've done all coding according to instruction till the end of Enable Authentication section.
But when trying to test the app I encounter with the following message:
`2021-11-13 09:42:17.083 4741-4741/? E/AuthUI: A sign-in error occurred.
    com.google.firebase.FirebaseException: An internal error has occurred. [ API key not valid. Please pass a valid API key. ]
        at com.google.android.gms.internal.firebase-auth-api.zzto.zza(com.google.firebase:firebase-auth@@21.0.1:4)
        at com.google.android.gms.internal.firebase-auth-api.zzuw.zza(com.google.firebase:firebase-auth@@21.0.1:9)
        at com.google.android.gms.internal.firebase-auth-api.zzux.zzl(com.google.firebase:firebase-auth@@21.0.1:1)
        at com.google.android.gms.internal.firebase-auth-api.zzuu.zzk(com.google.firebase:firebase-auth@@21.0.1:25)
        at com.google.android.gms.internal.firebase-auth-api.zztl.zzh(com.google.firebase:firebase-auth@@21.0.1:1)
        at com.google.android.gms.internal.firebase-auth-api.zzoj.zza(com.google.firebase:firebase-auth@@21.0.1:2)
        at com.google.android.gms.internal.firebase-auth-api.zzvb.zza(com.google.firebase:firebase-auth@@21.0.1:23)
        at com.google.android.gms.internal.firebase-auth-api.zzul.zza(com.google.firebase:firebase-auth@@21.0.1:4)
        at com.google.android.gms.internal.firebase-auth-api.zzpt.zzq(com.google.firebase:firebase-auth@@21.0.1:4)
        at com.google.android.gms.internal.firebase-auth-api.zztp.zzl(com.google.firebase:firebase-auth@@21.0.1:5)
        at com.google.android.gms.internal.firebase-auth-api.zzql.zzd(com.google.firebase:firebase-auth@@21.0.1:3)
        at com.google.android.gms.internal.firebase-auth-api.zzqk.accept(Unknown Source:6)
        at com.google.android.gms.common.api.internal.zacj.doExecute(com.google.android.gms:play-services-base@@17.5.0:2)
        at com.google.android.gms.common.api.internal.zah.zaa(com.google.android.gms:play-services-base@@17.5.0:9)
        at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zac(com.google.android.gms:play-services-base@@17.5.0:193)
        at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zab(com.google.android.gms:play-services-base@@17.5.0:158)
        at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zaa(com.google.android.gms:play-services-base@@17.5.0:126)
        at com.google.android.gms.common.api.internal.GoogleApiManager.handleMessage(com.google.android.gms:play-services-base@@17.5.0:164)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
`
It seems the the API key given in mock-google-services.json has expired.
What's the solution for this issue?

**Comment by mdsadiqueinam** [comment]
The issue is something else I used my own Firebase account but getting same issue

**Comment by mdsadiqueinam** [comment]
Found the solution, the issue is occurring because 
`if (BuildConfig.DEBUG) {
            FirebaseDatabase.getInstance().useEmulator("10.0.2.2", 9000)
            FirebaseAuth.getInstance().useEmulator("10.0.2.2", 9099);
            FirebaseStorage.getInstance().useEmulator("10.0.2.2", 9199)
        }`
here `BuildConfig.DEBUG` is giving false when app build, that why the emulator is not connection with app

**Comment by behhak** [comment]
"make sure BuildConfig is imported from Build generated file"
How?

**Comment by mdsadiqueinam** [comment]
before pasting the above code on `onCreate` method go to `Build -> Rebuild project` it will create an `Java (generated)` folder which contains the `BuildConfig` file use that `BuildConfig`

**Comment by jquinterom** [comment]
> The issue is something else I used my own Firebase account but getting same issue

Me too. I can't found the API KEY

**Comment by DevinRC** [comment]
> > "make sure BuildConfig is imported from Build generated file" How?
> 
> before pasting the above code on `onCreate` method go to `Build -> Rebuild project` it will create an `Java (generated)` folder which contains the `BuildConfig` file use that `BuildConfig`

Can you please elaborate further? I bypassed the `if (BuildConfig.DEBUG)` condition by setting it to True, but I still get an exception that the API key is invalid.
I believe the issue is lying with the key truly being expired/invalid, and not with the application logic.

**Comment by mdsadiqueinam** [comment]
> > > "make sure BuildConfig is imported from Build generated file" How?
> > 
> > 
> > before pasting the above code on `onCreate` method go to `Build -> Rebuild project` it will create an `Java (generated)` folder which contains the `BuildConfig` file use that `BuildConfig`
> 
> Can you please elaborate further? I bypassed the `if (BuildConfig.DEBUG)` condition by setting it to True, but I still get an exception that the API key is invalid. I believe the issue is lying with the key truly being expired/invalid, and not with the application logic.

Actually the key is truly invalid, but local emulator does not require any valid api key, so for time being use all the code inside `if (BuildConfig.DEBUG)` without `if`

**Comment by DevinRC** [comment]
### SignInActivity.kt
```
override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    // This codelab uses View Binding
    // See: https://developer.android.com/topic/libraries/view-binding
    binding = ActivitySignInBinding.inflate(layoutInflater)
    setContentView(binding.root)

    // Initialize FirebaseAuth
    auth = Firebase.auth    <-- Wrong code
}
```
Turns out I was having a code segment in the wrong place. Removing it fixed the issue. 
There is nothing wrong with the API key at the time of writing. 
Try comparing your code with the provided solution in the `\codelab-friendlychat-android\build-android` folder

**Comment by nishatoma** [comment]
Was anyone able to resolve this issue?

**Comment by hebadi** [comment]
Hello its June 23 and I'm still having this same issue today. "E/AuthUI: A sign-in error occurred."
> Turns out I was having a code segment in the wrong place.
this was definitely not my issue, but just to be certain I copied the whole SignInActivity and MainActivity from the completed version and pasted it onto my version. The difference I noticed was the code lab said to put some code into the onCreate and the completed one put it instead it onStart. Not sure how much of a difference that made but for my issue, it persisted nonetheless after doing this direct copy paste. 

> I was using the wrong BuildConfig class
This was also not my issue, I control click the class and see its from the appropriate "build" folder that was generated.

So, I'm stuck. How do i move forward? i would love some guidance here

**Comment by skille7** [comment]
> > "make sure BuildConfig is imported from Build generated file" How?
> 
> before pasting the above code on `onCreate` method go to `Build -> Rebuild project` it will create an `Java (generated)` folder which contains the `BuildConfig` file use that `BuildConfig`

fake you

**Comment by artikson** [comment]
> > > > > "make sure BuildConfig is imported from Build generated file" How?
> > > > 
> > > > 
> > > > before pasting the above code on `onCreate` method go to `Build -> Rebuild project` it will create an `Java (generated)` folder which contains the `BuildConfig` file use that `BuildConfig`
> > > 
> > > 
> > > Can you please elaborate further? I bypassed the `if (BuildConfig.DEBUG)` condition by setting it to True, but I still get an exception that the API key is invalid. I believe the issue is lying with the key truly being expired/invalid, and not with the application logic.
> > 
> > 
> > Actually the key is truly invalid, but local emulator does not require any valid api key, so for time being use all the code inside `if (BuildConfig.DEBUG)` without `if`
> 
> if anyone else runs into this, just add `buildConfig = true` to the `buildFeatures` in `app/build.gradle.kts`:
> 
> ```
>     buildFeatures {
>         viewBinding = true
>         buildConfig = true
>     }
> ```
> 
> After that rebuild project via ide or run `gradle clean build`.

Thank u, mate, that's make a trick for me.
