### ISSUE TITLE
com.firebaseui:firebase-ui-auth needs an upgrade

### ISSUE THREAD

**Issue by amazingvoice** [firebase/codelab-friendlychat-android#294]
Removing Credentials API in play-services-auth 21.0.0 breaks the code. It seems the newest com.firebaseui:firebase-ui-auth version 8.0.2 wasn't adjust for the change. 

The crash stacktrace is as follows:

FATAL EXCEPTION: main
                                                                                                    Process: com.google.firebase.codelab.friendlychat, PID: 16298
                                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/auth/api/credentials/CredentialsOptions$Builder;
                                                                                                    	at com.firebase.ui.auth.util.GoogleApiUtils.getCredentialsClient(GoogleApiUtils.java:29)
                                                                                                    	at com.firebase.ui.auth.viewmodel.AuthViewModelBase.onCreate(AuthViewModelBase.java:30)
                                                                                                    	at com.firebase.ui.auth.viewmodel.ViewModelBase.init(ViewModelBase.java:24)
                                                                                                    	at com.firebase.ui.auth.KickoffActivity.onCreate(KickoffActivity.java:38)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8305)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8284)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.auth.api.credentials.CredentialsOptions$Builder" on path: DexPathList[[dex file "/data/data/com.google.firebase.codelab.friendlychat/code_cache/.overlay/base.apk/classes4.dex", zip file "/data/app/~~L54qakZHHuiRLHkqjgYStg==/com.google.firebase.codelab.friendlychat-3tZsrpx2dhiiLQdJwdAmbw==/base.apk"],nativeLibraryDirectories=[/data/app/~~L54qakZHHuiRLHkqjgYStg==/com.google.firebase.codelab.friendlychat-3tZsrpx2dhiiLQdJwdAmbw==/lib/x86_64, /system/lib64, /system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at com.firebase.ui.auth.util.GoogleApiUtils.getCredentialsClient(GoogleApiUtils.java:29) 
                                                                                                    	at com.firebase.ui.auth.viewmodel.AuthViewModelBase.onCreate(AuthViewModelBase.java:30) 
                                                                                                    	at com.firebase.ui.auth.viewmodel.ViewModelBase.init(ViewModelBase.java:24) 
                                                                                                    	at com.firebase.ui.auth.KickoffActivity.onCreate(KickoffActivity.java:38) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8305) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8284) 
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417) 
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626) 
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by Anas010303** [comment]
In `\build-android-start\app\build.gradle.kts`, downgrade to 20.7.0:

```implementation("com.google.android.gms:play-services-auth:20.7.0")```

**Comment by marcardar** [comment]
2 months on and still no update :(

**Comment by inKevinA** [comment]
Up ?

**Comment by n-abdelmaksoud** [comment]
It is time to replace FirebaseAuth-UI. No updates Since Sep 2022!!
https://github.com/firebase/FirebaseUI-Android/releases/latest

**Comment by marklwembe** [comment]
As @Anas010303  mention the reason behind this is explained in this [StackOverflow](https://stackoverflow.com/a/78107308/9913649) answer. You have two options downgrade the version of the auth dependency you're using or use Credentials Manager instead.

With something like this codelab which was last updated a month ago the maintainer(s) should do a step by step walkthrough of the codelab to make sure that something hasn't become broken. Also guys this codelab is being maintained for free so be kind. No one is being paid here to handle negativity and I believe if you know how to fix the problem and have the time consider becoming a contributer. The more people working on this the more likely we are to avoid another [Linux-Backdoor-Situation](https://www.youtube.com/watch?v=jqjtNDtbDNI) by having as many [Andres Freunds](https://www.npr.org/2024/04/11/1244174104/one-engineer-may-have-saved-the-world-from-a-massive-cyber-attack#:~:text=Andres%20Freund%20works%20as%20a,found%20a%20sort%20of%20backdoor.) as possible

**Comment by n-abdelmaksoud** [comment]
> With something like this codelab which was last updated a month ago the maintainer(s) should do a step by step walkthrough of the codelab to make sure that something hasn't become broken. Also guys this codelab is being maintained for free so be kind. No one is being paid here to handle negativity and I believe if you know how to fix the problem and have the time consider becoming a contributer.

Thanks to everyone helped to share these codelabs, really very helpful specially for beginners. 
I was talking about Firebase Auth-UI library, it's not good solution to use any more specially in production apps. It was last updated more than 2 years ago and downgrading is not good solution if you have to target latest sdk.

**Comment by thatfiredev** [comment]
Hey all,
FirebaseUI Android [v9.0.0](https://github.com/firebase/FirebaseUI-Android/releases/tag/9.0.0) has been released and it solves the issue mentioned above.
This codelab was also updated in #329 to use that version, so the bug should now be fixed.
I'll close this issue now, but please let me know if you're still seeing the error.
