### ISSUE TITLE
###APP is Crashing --ASAP(i have project submission trying this from the past intense 12 hr )🙏 

### ISSUE THREAD

**Issue by ghost** [firebase/codelab-friendlychat-android#317]
i have an the app crashing in emulator as soon as it start

**Comment by morganchen12** [comment]
Can you share a stack trace and what step of the codelab you're on?

**Comment by Rengoku-demon** [comment]
here's my stack-trace :
2024-11-18 09:40:10.192  3946-3946  AndroidRuntime          com...firebase.codelab.friendlychat  E  FATAL EXCEPTION: main
                                                                                                    Process: com.google.firebase.codelab.friendlychat, PID: 3946
                                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/auth/api/credentials/CredentialsOptions$Builder;
                                                                                                    	at com.firebase.ui.auth.util.GoogleApiUtils.getCredentialsClient(GoogleApiUtils.java:29)
                                                                                                    	at com.firebase.ui.auth.viewmodel.AuthViewModelBase.onCreate(AuthViewModelBase.java:30)
                                                                                                    	at com.firebase.ui.auth.viewmodel.ViewModelBase.init(ViewModelBase.java:24)
                                                                                                    	at com.firebase.ui.auth.KickoffActivity.onCreate(KickoffActivity.java:38)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:9002)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8980)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1526)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4030)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4235)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:112)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:174)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:109)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2636)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8705)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.auth.api.credentials.CredentialsOptions$Builder" on path: DexPathList[[zip file "/data/app/~~dSKqiqtyAmh4KIkhmRvR0w==/com.google.firebase.codelab.friendlychat-kVX9Csrlx7zo9X4U6PO8zQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~dSKqiqtyAmh4KIkhmRvR0w==/com.google.firebase.codelab.friendlychat-kVX9Csrlx7zo9X4U6PO8zQ==/lib/arm64, /system/lib64, /system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:637)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
                                                                                                    	at com.firebase.ui.auth.util.GoogleApiUtils.getCredentialsClient(GoogleApiUtils.java:29) 
                                                                                                    	at com.firebase.ui.auth.viewmodel.AuthViewModelBase.onCreate(AuthViewModelBase.java:30) 
                                                                                                    	at com.firebase.ui.auth.viewmodel.ViewModelBase.init(ViewModelBase.java:24) 
                                                                                                    	at com.firebase.ui.auth.KickoffActivity.onCreate(KickoffActivity.java:38) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:9002) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8980) 
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1526) 
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4030) 
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4235) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:112) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:174) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:109) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2636) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232) 
                                                                                                    	at android.os.Looper.loop(Looper.java:317) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8705) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886) 
 
and im at the 5.Run the starter app

**Comment by Rengoku-demon** [comment]
> Can you share a stack trace and what step of the codelab you're on?

here's my stack-trace :
2024-11-18 09:40:10.192 3946-3946 AndroidRuntime com...firebase.codelab.friendlychat E FATAL EXCEPTION: main
Process: com.google.firebase.codelab.friendlychat, PID: 3946
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/auth/api/credentials/CredentialsOptions$Builder;
at com.firebase.ui.auth.util.GoogleApiUtils.getCredentialsClient(GoogleApiUtils.java:29)
at com.firebase.ui.auth.viewmodel.AuthViewModelBase.onCreate(AuthViewModelBase.java:30)
at com.firebase.ui.auth.viewmodel.ViewModelBase.init(ViewModelBase.java:24)
at com.firebase.ui.auth.KickoffActivity.onCreate(KickoffActivity.java:38)
at android.app.Activity.performCreate(Activity.java:9002)
at android.app.Activity.performCreate(Activity.java:8980)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1526)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4030)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4235)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:112)
at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:174)
at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:109)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2636)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loopOnce(Looper.java:232)
at android.os.Looper.loop(Looper.java:317)
at android.app.ActivityThread.main(ActivityThread.java:8705)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.auth.api.credentials.CredentialsOptions$Builder" on path: DexPathList[[zip file "/data/app/~~dSKqiqtyAmh4KIkhmRvR0w==/com.google.firebase.codelab.friendlychat-kVX9Csrlx7zo9X4U6PO8zQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~dSKqiqtyAmh4KIkhmRvR0w==/com.google.firebase.codelab.friendlychat-kVX9Csrlx7zo9X4U6PO8zQ==/lib/arm64, /system/lib64, /system_ext/lib64]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
at java.lang.ClassLoader.loadClass(ClassLoader.java:637)
at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
at com.firebase.ui.auth.util.GoogleApiUtils.getCredentialsClient(GoogleApiUtils.java:29) 
at com.firebase.ui.auth.viewmodel.AuthViewModelBase.onCreate(AuthViewModelBase.java:30) 
at com.firebase.ui.auth.viewmodel.ViewModelBase.init(ViewModelBase.java:24) 
at com.firebase.ui.auth.KickoffActivity.onCreate(KickoffActivity.java:38) 
at android.app.Activity.performCreate(Activity.java:9002) 
at android.app.Activity.performCreate(Activity.java:8980) 
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1526) 
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4030) 
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4235) 
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:112) 
at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:174) 
at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:109) 
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2636) 
at android.os.Handler.dispatchMessage(Handler.java:107) 
at android.os.Looper.loopOnce(Looper.java:232) 
at android.os.Looper.loop(Looper.java:317) 
at android.app.ActivityThread.main(ActivityThread.java:8705) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886) 

and im at the 5.Run the starter app

**Comment by morganchen12** [comment]
Seems like you're running into this issue: https://stackoverflow.com/questions/78103881/firebase-auth-failed-resolution-of-lcom-google-android-gms-auth-api-credential

You can pin the Auth version to 20.7.0 for now. To fix this issue the codelab needs to be updated.

**Comment by morganlilbook** [comment]
Lcom/google/android/gms/auth/api/credentials/CredentialsOptions$Builder
