### ISSUE TITLE
Image upload doesn't work

### ISSUE THREAD

**Issue by aleksandar-stefanovic** [firebase/codelab-friendlychat-android#49]
After choosing the image to be uploaded, it just shows the spinner indefinitely. The errors mention that "Firebase Storage should be enabled", so once enabled, the image upload works.

 This is the error stack trace:

```
E/StorageException: StorageException has occurred.
                    An unknown error occurred, please check the HTTP result code and inner exception for server response.
                     Code: -13000 HttpResult: 400
E/StorageException: The server has terminated the upload session
                    java.io.IOException: The server has terminated the upload session
                        at com.google.firebase.storage.UploadTask.zzs(Unknown Source:20)
                        at com.google.firebase.storage.UploadTask.zzr(Unknown Source:57)
                        at com.google.firebase.storage.UploadTask.run(Unknown Source:167)
                        at com.google.firebase.storage.StorageTask.zzl(Unknown Source:0)
                        at com.google.firebase.storage.zzq.run(Unknown Source:2)
                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                        at java.lang.Thread.run(Thread.java:764)
                     Caused by: java.io.IOException: {  "error": {    "code": 400,    "message": "Permission denied. Could not access bucket friendlychat-46567.appspot.com. Please enable Firebase Storage for your bucket by visiting the Storage tab in the Firebase Console and ensure that you have sufficient permission to properly provision resources."  }}
                        at bha.a(:com.google.android.gms.dynamite_dynamitemodulesc@12673023@12.6.73 (040400-194189626):147)
                        at bha.a(:com.google.android.gms.dynamite_dynamitemodulesc@12673023@12.6.73 (040400-194189626):119)
                        at bgu.onTransact(:com.google.android.gms.dynamite_dynamitemodulesc@12673023@12.6.73 (040400-194189626):7)
                        at android.os.Binder.transact(Binder.java:627)
                        at com.google.android.gms.internal.firebase_storage.zza.transactAndReadExceptionReturnVoid(Unknown Source:7)
                        at com.google.android.gms.internal.firebase_storage.zzm.zzf(Unknown Source:8)
                        at com.google.android.gms.internal.firebase_storage.zzq.zza(Unknown Source:41)
                        at com.google.android.gms.internal.firebase_storage.zzf.zza(Unknown Source:27)
                        at com.google.firebase.storage.UploadTask.zzc(Unknown Source:3)
                        at com.google.firebase.storage.UploadTask.run(Unknown Source:128)
                        at com.google.firebase.storage.StorageTask.zzl(Unknown Source:0) 
                        at com.google.firebase.storage.zzq.run(Unknown Source:2) 
                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                        at java.lang.Thread.run(Thread.java:764) 
                    StorageException has occurred.
                    An unknown error occurred, please check the HTTP result code and inner exception for server response.
                     Code: -13000 HttpResult: 400
E/StorageException: The server has terminated the upload session
                    java.io.IOException: The server has terminated the upload session
                        at com.google.firebase.storage.UploadTask.zzs(Unknown Source:20)
                        at com.google.firebase.storage.UploadTask.zzr(Unknown Source:57)
                        at com.google.firebase.storage.UploadTask.run(Unknown Source:167)
                        at com.google.firebase.storage.StorageTask.zzl(Unknown Source:0)
                        at com.google.firebase.storage.zzq.run(Unknown Source:2)
                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                        at java.lang.Thread.run(Thread.java:764)
                     Caused by: java.io.IOException: {  "error": {    "code": 400,    "message": "Permission denied. Could not access bucket friendlychat-46567.appspot.com. Please enable Firebase Storage for your bucket by visiting the Storage tab in the Firebase Console and ensure that you have sufficient permission to properly provision resources."  }}
                        at bha.a(:com.google.android.gms.dynamite_dynamitemodulesc@12673023@12.6.73 (040400-194189626):147)
                        at bha.a(:com.google.android.gms.dynamite_dynamitemodulesc@12673023@12.6.73 (040400-194189626):119)
                        at bgu.onTransact(:com.google.android.gms.dynamite_dynamitemodulesc@12673023@12.6.73 (040400-194189626):7)
                        at android.os.Binder.transact(Binder.java:627)
                        at com.google.android.gms.internal.firebase_storage.zza.transactAndReadExceptionReturnVoid(Unknown Source:7)
                        at com.google.android.gms.internal.firebase_storage.zzm.zzf(Unknown Source:8)
                        at com.google.android.gms.internal.firebase_storage.zzq.zza(Unknown Source:41)
                        at com.google.android.gms.internal.firebase_storage.zzf.zza(Unknown Source:27)
                        at com.google.firebase.storage.UploadTask.zzc(Unknown Source:3)
                        at com.google.firebase.storage.UploadTask.run(Unknown Source:128)
                        at com.google.firebase.storage.StorageTask.zzl(Unknown Source:0) 
                        at com.google.firebase.storage.zzq.run(Unknown Source:2) 
                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                        at java.lang.Thread.run(Thread.java:764) 
E/StorageException: StorageException has occurred.
                    An unknown error occurred, please check the HTTP result code and inner exception for server response.
                     Code: -13000 HttpResult: 400
E/StorageException: The server has terminated the upload session
                    java.io.IOException: The server has terminated the upload session
                        at com.google.firebase.storage.UploadTask.zzs(Unknown Source:20)
                        at com.google.firebase.storage.UploadTask.zzr(Unknown Source:57)
                        at com.google.firebase.storage.UploadTask.run(Unknown Source:167)
                        at com.google.firebase.storage.StorageTask.zzl(Unknown Source:0)
                        at com.google.firebase.storage.zzq.run(Unknown Source:2)
                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                        at java.lang.Thread.run(Thread.java:764)
                     Caused by: java.io.IOException: {  "error": {    "code": 400,    "message": "Permission denied. Could not access bucket friendlychat-46567.appspot.com. Please enable Firebase Storage for your bucket by visiting the Storage tab in the Firebase Console and ensure that you have sufficient permission to properly provision resources."  }}
                        at bha.a(:com.google.android.gms.dynamite_dynamitemodulesc@12673023@12.6.73 (040400-194189626):147)
                        at bha.a(:com.google.android.gms.dynamite_dynamitemodulesc@12673023@12.6.73 (040400-194189626):119)
                        at bgu.onTransact(:com.google.android.gms.dynamite_dynamitemodulesc@12673023@12.6.73 (040400-194189626):7)
                        at android.os.Binder.transact(Binder.java:627)
                        at com.google.android.gms.internal.firebase_storage.zza.transactAndReadExceptionReturnVoid(Unknown Source:7)
                        at com.google.android.gms.internal.firebase_storage.zzm.zzf(Unknown Source:8)
                        at com.google.android.gms.internal.firebase_storage.zzq.zza(Unknown Source:41)
                        at com.google.android.gms.internal.firebase_storage.zzf.zza(Unknown Source:27)
                        at com.google.firebase.storage.UploadTask.zzc(Unknown Source:3)
                        at com.google.firebase.storage.UploadTask.run(Unknown Source:128)
                        at com.google.firebase.storage.StorageTask.zzl(Unknown Source:0) 
                        at com.google.firebase.storage.zzq.run(Unknown Source:2) 
                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                        at java.lang.Thread.run(Thread.java:764) 
W/MainActivity: Image upload task was not successful.
                com.google.firebase.storage.StorageException: An unknown error occurred, please check the HTTP result code and inner exception for server response.
                    at com.google.firebase.storage.UploadTask.zza(Unknown Source:13)
                    at com.google.firebase.storage.StorageTask.zzh(Unknown Source:3)
                    at com.google.firebase.storage.StorageTask.zzi(Unknown Source:19)
                    at com.google.firebase.storage.StorageTask.getException(Unknown Source:0)
                    at com.google.firebase.codelab.friendlychat.MainActivity$7.onComplete(MainActivity.java:380)
                    at com.google.firebase.storage.zzl.zza(Unknown Source:11)
                    at com.google.firebase.storage.zzaa.run(Unknown Source:10)
                    at android.os.Handler.handleCallback(Handler.java:790)
                    at android.os.Handler.dispatchMessage(Handler.java:99)
                    at android.os.Looper.loop(Looper.java:164)
                    at android.app.ActivityThread.main(ActivityThread.java:6494)
                    at java.lang.reflect.Method.invoke(Native Method)
                    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                 Caused by: java.io.IOException: The server has terminated the upload session
                    at com.google.firebase.storage.UploadTask.zzs(Unknown Source:20)
                    at com.google.firebase.storage.UploadTask.zzr(Unknown Source:57)
                    at com.google.firebase.storage.UploadTask.run(Unknown Source:167)
                    at com.google.firebase.storage.StorageTask.zzl(Unknown Source:0)
                    at com.google.firebase.storage.zzq.run(Unknown Source:2)
                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                    at java.lang.Thread.run(Thread.java:764)
                 Caused by: java.io.IOException: {  "error": {    "code": 400,    "message": "Permission denied. Could not access bucket friendlychat-46567.appspot.com. Please enable Firebase Storage for your bucket by visiting the Storage tab in the Firebase Console and ensure that you have sufficient permission to properly provision resources."  }}
                    at bha.a(:com.google.android.gms.dynamite_dynamitemodulesc@12673023@12.6.73 (040400-194189626):147)
                    at bha.a(:com.google.android.gms.dynamite_dynamitemodulesc@12673023@12.6.73 (040400-194189626):119)
                    at bgu.onTransact(:com.google.android.gms.dynamite_dynamitemodulesc@12673023@12.6.73 (040400-194189626):7)
                    at android.os.Binder.transact(Binder.java:627)
                    at com.google.android.gms.internal.firebase_storage.zza.transactAndReadExceptionReturnVoid(Unknown Source:7)
                    at com.google.android.gms.internal.firebase_storage.zzm.zzf(Unknown Source:8)
                    at com.google.android.gms.internal.firebase_storage.zzq.zza(Unknown Source:41)
                    at com.google.android.gms.internal.firebase_storage.zzf.zza(Unknown Source:27)
                    at com.google.firebase.storage.UploadTask.zzc(Unknown Source:3)
                    at com.google.firebase.storage.UploadTask.run(Unknown Source:128)
                    at com.google.firebase.storage.StorageTask.zzl(Unknown Source:0) 
                    at com.google.firebase.storage.zzq.run(Unknown Source:2) 
                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                    at java.lang.Thread.run(Thread.java:764) 
```

**Comment by Arthurin** [comment]
Same issue here ! :/

**Comment by zameerhossain** [comment]
how did you all solve this problem same issue here
